/* tslint:disable */
/* eslint-disable */
/**
 * tlsnotary-and-cartesi-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface HealthCheck200Response
 */
export interface HealthCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck200Response
     */
    'status'?: string;
    /**
     * 
     * @type {{ [key: string]: HealthCheck200ResponseInfoValue; }}
     * @memberof HealthCheck200Response
     */
    'info'?: { [key: string]: HealthCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthCheck200ResponseInfoValue; }}
     * @memberof HealthCheck200Response
     */
    'error'?: { [key: string]: HealthCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthCheck200ResponseInfoValue; }}
     * @memberof HealthCheck200Response
     */
    'details'?: { [key: string]: HealthCheck200ResponseInfoValue; };
}
/**
 * 
 * @export
 * @interface HealthCheck200ResponseInfoValue
 */
export interface HealthCheck200ResponseInfoValue {
    [key: string]: string;

    /**
     * 
     * @type {string}
     * @memberof HealthCheck200ResponseInfoValue
     */
    'status'?: string;
}
/**
 * 
 * @export
 * @interface HealthCheck503Response
 */
export interface HealthCheck503Response {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck503Response
     */
    'status'?: string;
    /**
     * 
     * @type {{ [key: string]: HealthCheck200ResponseInfoValue; }}
     * @memberof HealthCheck503Response
     */
    'info'?: { [key: string]: HealthCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthCheck200ResponseInfoValue; }}
     * @memberof HealthCheck503Response
     */
    'error'?: { [key: string]: HealthCheck200ResponseInfoValue; } | null;
    /**
     * 
     * @type {{ [key: string]: HealthCheck200ResponseInfoValue; }}
     * @memberof HealthCheck503Response
     */
    'details'?: { [key: string]: HealthCheck200ResponseInfoValue; };
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheck(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthCheck200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck(options?: any): AxiosPromise<HealthCheck200Response> {
            return localVarFp.healthCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheck(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheck(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ProofApi - axios parameter creator
 * @export
 */
export const ProofApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get user KYC proof
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProof: async (userId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getProof', 'userId', userId)
            const localVarPath = `/v1/proofs/kyc/users/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify KYC proof
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyKycProof: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/proofs/kyc/verifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProofApi - functional programming interface
 * @export
 */
export const ProofApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProofApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get user KYC proof
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProof(userId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProof(userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Verify KYC proof
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyKycProof(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyKycProof(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProofApi - factory interface
 * @export
 */
export const ProofApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProofApiFp(configuration)
    return {
        /**
         * 
         * @summary Get user KYC proof
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProof(userId: number, options?: any): AxiosPromise<void> {
            return localVarFp.getProof(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify KYC proof
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyKycProof(options?: any): AxiosPromise<string> {
            return localVarFp.verifyKycProof(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProofApi - object-oriented interface
 * @export
 * @class ProofApi
 * @extends {BaseAPI}
 */
export class ProofApi extends BaseAPI {
    /**
     * 
     * @summary Get user KYC proof
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProofApi
     */
    public getProof(userId: number, options?: AxiosRequestConfig) {
        return ProofApiFp(this.configuration).getProof(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify KYC proof
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProofApi
     */
    public verifyKycProof(options?: AxiosRequestConfig) {
        return ProofApiFp(this.configuration).verifyKycProof(options).then((request) => request(this.axios, this.basePath));
    }
}



