# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: microservice-nestjs-template CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        node-version: [10.x, 12.x, 14.x]
        node-version: [18.x]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: work around https://github.com/actions/checkout/issues/211#issuecomment-611986243
        run: sudo chown -R $USER:$USER /home/*

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Prepare .env
        run: npm run env:config ci

      - name: Install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
          npm ci

      # Run tests
      - name: Test
        run: npm run test

      - name: e2e Test
        run: npm run docker-compose:test:e2e

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: work around https://github.com/actions/checkout/issues/211#issuecomment-611986243
        run: sudo chown -R $USER:$USER /home/*


      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::940355036220:role/github-actions-role
          role-session-name: github-actions-role
          aws-region: us-east-1

      - name: Prepare .env
        run: npm run env:config ci

      - name: Install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${NPM_TOKEN}
          npm ci

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
